//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ECommerceEntities_Top10XML : DbContext
    {
        public ECommerceEntities_Top10XML()
            : base("name=ECommerceEntities_Top10XML")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<USP_TOP10XML_Result> USP_TOP10XML()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_TOP10XML_Result>("USP_TOP10XML");
        }
    }
}
