USE MASTER;
GO
IF EXISTS(SELECT *
		FROM	master..sysdatabases
		WHERE	name = N'ECommerce')
DROP DATABASE ECommerce;	
GO
CREATE DATABASE ECommerce;
GO
USE ECommerce;
SET DATEFORMAT dmy;
GO

DROP TABLE IF EXISTS [TOP10SELLER];
DROP TABLE IF EXISTS [ORDER];
DROP TABLE IF EXISTS [PRODUCT];
DROP TABLE IF EXISTS [IMGURL];
DROP TABLE IF EXISTS [ORDERITEM];
DROP TABLE IF EXISTS [CATEGORY];
DROP TABLE IF EXISTS [KEYWORDS];


CREATE TABLE [dbo].[KEYWORDS] (
	[keyword]		NVARCHAR  (20)					NOT NULL,
	CONSTRAINT [KEYWORDS_pk] PRIMARY KEY ([keyword])
);
GO


CREATE TABLE [dbo].[ORDER] (
	[orderID]		INT		IDENTITY (1001, 1)		NOT NULL,
	[email]			NVARCHAR (50)					NOT NULL,
	[payStatus]		BIT								NOT NULL,
	[orderTime]		DATETIME						NOT NULL,
	CONSTRAINT [ORDER_pk] PRIMARY KEY ([orderID])
);
GO

CREATE TABLE [dbo].[DELIVERYADDRESS]
(
    [orderID]     INT           NOT NULL,
    [firstName]   NVARCHAR (20) NOT NULL,
    [lastName]    NVARCHAR (20) NOT NULL,
    [street]      NVARCHAR (50) NOT NULL,
    [city]        NVARCHAR (20) NOT NULL,
    [state]       NVARCHAR (5)  NOT NULL,
    [postCode]    NVARCHAR (6)  NOT NULL,
    [phoneNumber] NVARCHAR (15) NOT NULL,
    CONSTRAINT [DELIVERYADDRESS_pk] PRIMARY KEY ([orderID]),
	CONSTRAINT [ORDER_DELIVERYADDRESS_fk] FOREIGN KEY ([orderID]) REFERENCES [ORDER] ([orderID])
);
GO


CREATE TABLE [dbo].[PRODUCT] (
	[productID]		INT		IDENTITY (1001, 1)		NOT NULL,
	[name]			NVARCHAR (100)					NOT NULL,
	[description]	NVARCHAR (MAX)					NOT NULL,
	[price]			DECIMAL							NOT NULL,
	CONSTRAINT [PRODUCT_pk] PRIMARY KEY ([productID])
);
GO

CREATE TABLE [dbo].[TOP10SELLER] (
	[productID]		INT		NOT NULL,
	[sales]			INT		NOT NULL,
	CONSTRAINT [TOP10SELLER_pk] PRIMARY KEY ([productID]),
	CONSTRAINT [PRODUCT_TOP10SELLER_fk] FOREIGN KEY ([productID]) REFERENCES [PRODUCT] (productID)
);
GO

CREATE TABLE [dbo].[IMGURL] (
	[imageURL]		NVARCHAR (50)					NOT NULL,
	[productID]		INT								NOT NULL,
	CONSTRAINT [IMGURL_pk] PRIMARY KEY ([imageURL]),
	CONSTRAINT [PRODUCT_IMAGEURL_fk] FOREIGN KEY ([productID]) REFERENCES [PRODUCT] ([productID])
);
GO

CREATE TABLE [dbo].[ORDERITEM] (
	[productID]		INT								NOT NULL,
	[orderID]		INT								NOT NULL,
	[quantity]		INT								NOT NULL,
	[price]			DECIMAL							NOT NULL,
	CONSTRAINT [ORDERITEM_pk] PRIMARY KEY ([productID], [orderID]),
	CONSTRAINT [ORDER_ORDERITEM_fk] FOREIGN KEY ([orderID]) REFERENCES [ORDER] ([orderID]),
	CONSTRAINT [PRODUCT_ORDERITEM_fk] FOREIGN KEY ([productID]) REFERENCES [PRODUCT] ([productID])
);
GO

CREATE TABLE [dbo].[CATEGORY] (
	[keyword]		NVARCHAR (20)					NOT NULL,
	[productID]		INT								NOT NULL,
	CONSTRAINT [CATEGORY_pk] PRIMARY KEY ([keyword],[productID]),
	CONSTRAINT [KEYWORS_CATEGORY_fk] FOREIGN KEY ([keyword]) REFERENCES [KEYWORDS] ([keyword]),
	CONSTRAINT [PRODUCT_CATEGORY_fk] FOREIGN KEY ([productID]) REFERENCES [PRODUCT] ([productID])
);
GO

