USE MASTER;
GO
IF EXISTS(SELECT *
		FROM	master..sysdatabases
		WHERE	name = N'ECommerce')
DROP DATABASE ECommerce;	
GO
CREATE DATABASE ECommerce;
GO
USE ECommerce;
SET DATEFORMAT dmy;
GO

DROP TABLE IF EXISTS [TOP10SELLER];
DROP TABLE IF EXISTS [ORDER];
DROP TABLE IF EXISTS [PRODUCT];
DROP TABLE IF EXISTS [IMGURL];
DROP TABLE IF EXISTS [ORDERITEM];
DROP TABLE IF EXISTS [PRODUCTCATEGORY];
DROP TABLE IF EXISTS [CATEGORY];


CREATE TABLE [KEYWORDS] (
	[keyword]		NVARCHAR  (20)					NOT NULL,
	CONSTRAINT [KEYWORDS_pk] PRIMARY KEY ([keyword])
);

CREATE TABLE [ORDER] (
	[orderID]		INT		IDENTITY (1001, 1)		NOT NULL,
	[email]			NVARCHAR (50)					NOT NULL,
	[payStatus]		BIT								NOT NULL,
	[orderTime]		DATETIME						NOT NULL,
	[fistname]		NVARCHAR (20)					NOT NULL,
	[lastname]		NVARCHAR (20)					NOT NULL,
	[street]		NVARCHAR (50)					NOT NULL,
	[city]			NVARCHAR (20)					NOT NULL,
	[state]			NVARCHAR (5)					NOT NULL,
	[postcode]		NVARCHAR (6)					NOT NULL,
	[phoneNumber]	NVARCHAR (15)					NOT NULL,
	CONSTRAINT [ORDER_pk] PRIMARY KEY ([orderID])
);
GO


CREATE TABLE [PRODUCT] (
	[productID]		INT		IDENTITY (1001, 1)		NOT NULL,
	[name]			NVARCHAR (100)					NOT NULL,
	[description]	NVARCHAR (MAX)					NOT NULL,
	[price]			DECIMAL							NOT NULL,
	CONSTRAINT [PRODUCT_pk] PRIMARY KEY ([productID])
);
GO

CREATE TABLE [TOP10SELLER] (
	[productID]		INT		NOT NULL,
	[sales]			INT		NOT NULL,
	CONSTRAINT [TOP10SELLER_pk] PRIMARY KEY ([productID])
);
GO

CREATE TABLE [IMGURL] (
	[imageURL]		NVARCHAR (50)					NOT NULL,
	[productID]		INT								NOT NULL,
	CONSTRAINT [IMGURL_pk] PRIMARY KEY ([imageURL])
);
GO

CREATE TABLE [ORDERITEM] (
	[productID]		INT								NOT NULL,
	[orderID]		INT								NOT NULL,
	[quantity]		INT								NOT NULL,
	[price]			DECIMAL							NOT NULL,
	CONSTRAINT [ORDERITEM_pk] PRIMARY KEY ([productID], [orderID])
);
GO

CREATE TABLE [CATEGORY] (
	[keyword]		NVARCHAR (20)					NOT NULL,
	[productID]		INT								NOT NULL,
	CONSTRAINT [CATEGORY_pk] PRIMARY KEY ([keyword],[productID])
);
GO


ALTER TABLE [IMGURL]	ADD CONSTRAINT [PRODUCT_IMAGEURL_fk] FOREIGN KEY ([productID]) REFERENCES [PRODUCT] ([productID]);
ALTER TABLE [ORDERITEM]	ADD CONSTRAINT [ORDER_ORDERITEM_fk] FOREIGN KEY ([orderID]) REFERENCES [ORDER] ([orderID]);
ALTER TABLE [ORDERITEM]	ADD CONSTRAINT [PRODUCT_ORDERITEM_fk] FOREIGN KEY ([productID]) REFERENCES [PRODUCT] ([productID]);
ALTER TABLE [CATEGORY] ADD CONSTRAINT [KEYWORS_CATEGORY_fk] FOREIGN KEY ([keyword]) REFERENCES [KEYWORDS] ([keyword]);
ALTER TABLE [CATEGORY]	ADD CONSTRAINT [PRODUCT_CATEGORY_fk] FOREIGN KEY ([productID]) REFERENCES [PRODUCT] ([productID]);
ALTER TABLE [TOP10SELLER] ADD CONSTRAINT [PRODUCT_TOP10SELLER_fk] FOREIGN KEY ([productID]) REFERENCES [PRODUCT] (productID);